version: 2

######### Variables #########

root-folder: &root-folder ~/push-for-github-mobile

######### Configs #########

node-config: &node-config
  working_directory: *root-folder
  docker:
    - image: circleci/node:11.10

######### Jobs #########

jobs:
  push-for-github-server-build:
    <<: *node-config
    steps:
      - checkout
      - run: echo TODO

######### Workflows #########

workflows:
  version: 2
  commit:
    jobs:
      - push-for-github-server-build
