version: 2

######### Common #########

root-folder: &root-folder ~/push-for-github
node-cache-key: &node-cache-key node-v1-{{ checksum "package.json" }}
yarn-cache-key: &yarn-cache-key yarn-v1-{{ checksum "~/push-for-github/yarn.lock" }}
node-docker-image: &node-docker-image circleci/node:11.10
should-run-command: &should-run-command . ../../.circleci/should-run.sh

should-run: &should-run
  name: stop if no changes
  command: *should-run-command
  environment:
    SHOULD_RUN_PACKAGE: NONE

restore-yarn-cache: &restore-yarn-cache
  restore_cache:
    key: *yarn-cache-key

restore-node-cache: &restore-node-cache
  restore_cache:
    key: *node-cache-key

yarn-install: &yarn-install
  run: yarn

save-yarn-cache: &save-yarn-cache
  save_cache:
    key: *yarn-cache-key
    paths:
      - ~/.cache/yarn

save-node-cache: &save-node-cache
  save_cache:
    key: *node-cache-key
    paths:
      - node_modules
      - ../../node_modules

master-branch-filter: &master-branch-filter
  filters:
    branches:
      only: master

any-tag: &any-tag
  tags:
    only: /.*/

develop-filters: &develop-filters
  filters:
    branches:
      only:
        - /f\/.*/
        - master

deploy-filters: &deploy-filters
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /\@([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/

######### push-for-github-server #########

push-for-github-server-folder: &push-for-github-server-folder ~/push-for-github/packages/push-for-github-server

push-for-github-server-config: &push-for-github-server-config
  working_directory: *push-for-github-server-folder
  docker:
    - image: *node-docker-image
  environment:
    DOCKER_REPO: negebauer/push-for-github-server

checkout-push-for-github-server: &checkout-push-for-github-server
  checkout:
    path: *root-folder

should-run-push-for-github-server: &should-run-push-for-github-server
  run:
    <<: *should-run
    environment:
      SHOULD_RUN_PACKAGE: push-for-github-server

######### Jobs #########

jobs:
  push-for-github-server-yarn:
    <<: *push-for-github-server-config
    steps:
      - *checkout-push-for-github-server
      - *should-run-push-for-github-server
      - *restore-yarn-cache
      - *restore-node-cache
      - *yarn-install
      - *save-yarn-cache
      - *save-node-cache

  push-for-github-server-linter:
    <<: *push-for-github-server-config
    steps:
      - *checkout-push-for-github-server
      - *should-run-push-for-github-server
      - *restore-yarn-cache
      - *restore-node-cache
      - run: echo TODO linter

  push-for-github-server-docker:
    <<: *push-for-github-server-config
    steps:
      - *checkout-push-for-github-server
      - *should-run-push-for-github-server
      - setup_remote_docker
      - run: docker build . -t $DOCKER_REPO
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push $DOCKER_REPO

######### Workflows #########

workflows:
  version: 2
  commit:
    jobs:
      - push-for-github-server-yarn
      - push-for-github-server-linter:
          requires:
            - push-for-github-server-yarn
      - push-for-github-server-docker:
          requires:
            - push-for-github-server-linter
          <<: *master-branch-filter
